### ISSUE TITLE
JsonMappingException when the client close the connection using the  StreamServer

### ISSUE THREAD

**Issue by fatihwk** [briandilley/jsonrpc4j#36] opened 2014-07-23 08:07 UTC
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: com.googlecode.jsonrpc4j.NoCloseInputStream@7de4e3e4; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3036)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2978)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1737)
	at com.googlecode.jsonrpc4j.JsonRpcServer.handle(JsonRpcServer.java:224)
	at com.googlecode.jsonrpc4j.StreamServer$Server.run(StreamServer.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)

in jackson library  if it reads null token follow null token.  it will throw the exception. should it check the connection status before parse the json stream? 

   protected JsonToken _initForReading(JsonParser jp)
        throws IOException, JsonParseException, JsonMappingException
    {
        /* First: must point to a token; if not pointing to one, advance.
         * This occurs before first read from JsonParser, as well as
         * after clearing of current token.
         */
        JsonToken t = jp.getCurrentToken();
        if (t == null) {
            // and then we must get something...
            t = jp.nextToken();
            if (t == null) {
                /* [JACKSON-546] Throw mapping exception, since it's failure to map,
                 *   not an actual parsing problem
                 */
                throw JsonMappingException.from(jp, "No content to map due to end-of-input");
            }
        }
        return t;
    }

**Comment by RuralHunter** [comment] 2015-01-28 06:13
This should be duplicate of #3. You can try 1.2-SNAPSHOT

**Comment by federicoon** [comment] 2015-02-16 17:48
I'm having this issue too with both version 1.1 and 1.2-SNAPSHOT.
Why was #3 closed? It doesn't seem fixed yet

**Closed** 2015-11-10 10:31 UTC
